// mobile/src/theme.js
import { StyleSheet } from 'react-native';

export const colors = {
  primary: '#4F46E5',
  primaryLight: '#EEF2FF',
  primaryDark: '#3730A3',
  success: '#059669',
  successLight: '#ECFDF5',
  danger: '#DC2626',
  dangerLight: '#FEF2F2',
  warning: '#D97706',
  warningLight: '#FFFBEB',
  gray50: '#F9FAFB',
  gray100: '#F3F4F6',
  gray200: '#E5E7EB',
  gray300: '#D1D5DB',
  gray500: '#6B7280',
  gray700: '#374151',
  gray900: '#111827',
  white: '#FFFFFF',
};

export const s = StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.gray50 },
  container: { flex: 1, padding: 16 },
  card: {
    backgroundColor: colors.white, borderRadius: 12,
    borderWidth: 1, borderColor: colors.gray200,
    padding: 16, marginBottom: 12,
    shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 4, elevation: 2,
  },
  h1: { fontSize: 22, fontWeight: '700', color: colors.gray900 },
  h2: { fontSize: 18, fontWeight: '600', color: colors.gray900 },
  h3: { fontSize: 16, fontWeight: '600', color: colors.gray900 },
  body: { fontSize: 14, color: colors.gray700, lineHeight: 20 },
  muted: { fontSize: 13, color: colors.gray500 },
  label: { fontSize: 13, fontWeight: '500', color: colors.gray700, marginBottom: 4 },
  input: {
    borderWidth: 1, borderColor: colors.gray300, borderRadius: 8,
    paddingHorizontal: 12, paddingVertical: 10, fontSize: 14,
    color: colors.gray900, backgroundColor: colors.white,
  },
  btnPrimary: {
    backgroundColor: colors.primary, borderRadius: 8,
    paddingVertical: 12, paddingHorizontal: 20, alignItems: 'center',
  },
  btnOutline: {
    backgroundColor: colors.white, borderRadius: 8, borderWidth: 1,
    borderColor: colors.gray300, paddingVertical: 10, paddingHorizontal: 16, alignItems: 'center',
  },
  btnText: { color: colors.white, fontWeight: '600', fontSize: 14 },
  btnOutlineText: { color: colors.gray700, fontWeight: '500', fontSize: 14 },
  btnDanger: { backgroundColor: colors.danger, borderRadius: 8, paddingVertical: 10, paddingHorizontal: 16, alignItems: 'center' },
  row: { flexDirection: 'row', alignItems: 'center' },
  between: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  badge: { paddingHorizontal: 10, paddingVertical: 2, borderRadius: 20 },
  badgePrimary: { backgroundColor: colors.primaryLight },
  badgePrimaryText: { color: colors.primary, fontSize: 12, fontWeight: '500' },
  badgeSuccess: { backgroundColor: colors.successLight },
  badgeSuccessText: { color: colors.success, fontSize: 12, fontWeight: '500' },
  badgeDanger: { backgroundColor: colors.dangerLight },
  badgeDangerText: { color: colors.danger, fontSize: 12, fontWeight: '500' },
  badgeWarning: { backgroundColor: colors.warningLight },
  badgeWarningText: { color: colors.warning, fontSize: 12, fontWeight: '500' },
  separator: { height: 1, backgroundColor: colors.gray200, marginVertical: 12 },
  center: { alignItems: 'center', justifyContent: 'center' },
  statCard: { backgroundColor: colors.gray50, borderRadius: 10, padding: 14, borderWidth: 1, borderColor: colors.gray200 },
});
